version: '3.2'
services:
  host:
    name: host
    build:
      context: .
      dockerfile: host.Dockerfile
    volumes:
      - type: "bind"
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
  
  sandbox:
    name: sandbox
    build:
      context: .
      dockerfile: sandbox.Dockerfile